FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir google-cloud-storage pandas scikit-learn joblib 

COPY app/train.py train.py

ENV PYTHONUNBUFFERED=1

# ENTRYPOINT ["python", "train.py"]